sudo: required
services: 
  - docker

before_install:
  - docker build -t lanceom/react-app-docker -f Dockerfile.dev .


script: 
  - docker run -e CI=true lanceom/react-app-docker npm run test -- --coverage